name: Build VCMP Kotlin Plugin

on:
  workflow_dispatch: # Run manually from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout vcmp-java-demo
      run: |
        git clone https://github.com/theKAKAN/vcmp-java-demo.git
        cd vcmp-java-demo

    - name: Install OpenJDK 8
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        java -version

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV

    - name: Build with Gradle
      working-directory: vcmp-java-demo
      run: ./gradlew shadowJar

    - name: Prepare download folder
      run: |
        mkdir -p public
        cp vcmp-java-demo/build/libs/*.jar public/

    - name: Download cloudflared
      run: |
        wget -q -nc https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
        chmod +x cloudflared

    - name: Start Web Server
      run: |
        nohup python3 -m http.server 10000 --directory public &

    - name: Start Cloudflared Tunnel
      run: |
        ./cloudflared tunnel --url http://127.0.0.1:10000 --metrics localhost:45678
