name: Build VCMP Java Plugin

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone VCMP Java Demo
        run: |
          git clone https://github.com/theKAKAN/vcmp-java-demo.git
          cd vcmp-java-demo
          ls -la

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Verify Java version
        run: |
          java -version
          javac -version

      - name: Download Dependencies
        run: |
          mkdir -p ~/.m2/repository/com/maxorator/vcmp/plugin
          cd ~/.m2/repository/com/maxorator/vcmp/plugin
          wget -r -np -nH --cut-dirs=4 -R "index.html*" https://v04.thijn.ovh/maven/com/maxorator/vcmp/plugin/
          ls -R

      - name: Build the Plugin
        run: |
          cd vcmp-java-demo
          javac -cp ~/.m2/repository com/maxorator/vcmp/plugin/*.java -d bin
          jar cf VCMPJavaDemo.jar -C bin .
          ls -la
